--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SAMPLE_TODO_USERS
--------------------------------------------------------

  CREATE TABLE "HR"."SAMPLE_TODO_USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(256 BYTE), 
	"USER_CREATED_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAMPLE_TODOS
--------------------------------------------------------

  CREATE TABLE "HR"."SAMPLE_TODOS" 
   (	"TODO_NO" NUMBER(6,0), 
	"TODO_TITLE" VARCHAR2(200 BYTE), 
	"TODO_CONTENT" VARCHAR2(2000 BYTE), 
	"TODO_DAY" DATE, 
	"TODO_COMPLETED_DAY" DATE, 
	"TODO_STATUS" VARCHAR2(200 BYTE) DEFAULT '처리예정', 
	"USER_ID" VARCHAR2(20 BYTE), 
	"TODO_CREATE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.SAMPLE_TODO_USERS
SET DEFINE OFF;
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun429','정다훈','123','dd@nn',to_date('20/07/06 10:39:20','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun421','정다훈','1234','rubcustomer@gmail.com',to_date('20/07/06 15:10:35','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun424','정다훈','ddd','rubcustomer@gmail.com',to_date('20/07/06 12:03:16','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun426','정다훈','1234','rubcustomer@gmail.com',to_date('20/07/06 11:20:07','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun428','정다훈','1234','rubcustomer@gmail.com',to_date('20/07/06 10:44:45','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun427','정다훈','1234','1234',to_date('20/07/06 11:18:24','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODO_USERS (USER_ID,USER_NAME,USER_PASSWORD,USER_EMAIL,USER_CREATED_DATE) values ('dahun425','정다훈','1234','rubcustomer@gmail.com',to_date('20/07/06 11:29:42','RR/MM/DD HH24:MI:SS'));
REM INSERTING into HR.SAMPLE_TODOS
SET DEFINE OFF;
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (1,'ㅇㅇㅇㅇㅇ','DF',to_date('20/07/07 00:00:00','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 15:32:16','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (2,'sdaf','asdf',to_date('20/07/08 00:00:00','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 15:36:39','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (3,'sdfasdf','sdafsadf',to_date('20/07/01 00:00:00','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 15:41:09','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (4,'일정4','테스트 일정',to_date('20/07/10 16:34:58','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:34:58','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (5,'일정5','테스트 일정',to_date('20/07/11 16:35:18','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:18','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (6,'일정6','테스트 일정',to_date('20/07/12 16:35:18','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:18','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (7,'일정7','테스트 일정',to_date('20/07/13 16:35:18','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:18','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (8,'일정8','테스트 일정',to_date('20/07/14 16:35:19','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:19','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (9,'일정9','테스트 일정',to_date('20/07/15 16:35:19','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:19','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (10,'일정10','테스트 일정',to_date('20/07/16 16:35:19','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:19','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (11,'일정11','테스트 일정',to_date('20/07/17 16:35:20','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:20','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (12,'일정12','테스트 일정',to_date('20/07/18 16:35:20','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:20','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (13,'일정13','테스트 일정',to_date('20/07/19 16:35:20','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:20','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (14,'일정14','테스트 일정',to_date('20/07/20 16:35:21','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:21','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (15,'일정15','테스트 일정',to_date('20/07/21 16:35:21','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:21','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (16,'일정16','테스트 일정',to_date('20/07/22 16:35:21','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:21','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (17,'일정17','테스트 일정',to_date('20/07/23 16:35:22','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:22','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (18,'일정18','테스트 일정',to_date('20/07/24 16:35:22','RR/MM/DD HH24:MI:SS'),null,'처리예정','dahun429',to_date('20/07/06 16:35:22','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (19,'일정19','테스트 일정',to_date('20/07/25 16:35:24','RR/MM/DD HH24:MI:SS'),null,'처리중','dahun429',to_date('20/07/06 16:35:24','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (20,'일정20','테스트 일정',to_date('20/07/26 16:35:24','RR/MM/DD HH24:MI:SS'),null,'처리중','dahun429',to_date('20/07/06 16:35:24','RR/MM/DD HH24:MI:SS'));
Insert into HR.SAMPLE_TODOS (TODO_NO,TODO_TITLE,TODO_CONTENT,TODO_DAY,TODO_COMPLETED_DAY,TODO_STATUS,USER_ID,TODO_CREATE_DATE) values (21,'일정21','테스트 일정',to_date('20/07/27 16:35:25','RR/MM/DD HH24:MI:SS'),null,'처리완료','dahun429',to_date('20/07/06 16:35:25','RR/MM/DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index SYS_C007458
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007458" ON "HR"."SAMPLE_TODO_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007464
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007464" ON "HR"."SAMPLE_TODOS" ("TODO_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SAMPLE_TODO_USERS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_TODO_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SAMPLE_TODO_USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_TODO_USERS" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_TODO_USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SAMPLE_TODOS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_TODOS" ADD PRIMARY KEY ("TODO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SAMPLE_TODOS" MODIFY ("TODO_DAY" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_TODOS" MODIFY ("TODO_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."SAMPLE_TODOS" MODIFY ("TODO_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SAMPLE_TODOS
--------------------------------------------------------

  ALTER TABLE "HR"."SAMPLE_TODOS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "HR"."SAMPLE_TODO_USERS" ("USER_ID") ENABLE;
